###############################################################################################################################################################################
#
# Version: ${project.version} (If this does not match your current plugin version then something went wrong while updating the config file!)
#
# Welcome to Deadly Disasters!
#
###############################################################################################################################################################################
#
# Here is a quick explanation of the different files in the plugins directory and how to setup and configure the plugin:
#
#   "config.yml" - [This file] Controls the general settings for the plugin, mainly admin settings and resource cap settings.
#
#   "worldConfigs/" - This is a folder in the plugins directory and should be auto populated with the default world config file. There is a separate config file that handles 
#                     all of the world settings for disasters occurring, timings, and individual settings. This is done so that you can configure worlds differently to fit 
#                     your needs. This folder is where you can add or copy new configs into and then point worlds to them in game via command (/disasters config set <world> <config>). 
#                     Multiple worlds can point to the same config file, by default all worlds will point to the default.yml config file in this folder. To create your own 
#                     world config file you can simply copy and paste the default.yml file, and change the name to whatever you want, then change the settings within. If you 
#                     make a config that really supports a certain type of gameplay style, feel free to share it in the discord for others to enjoy!
#
#   "language.yml" - This is the plugins language file. Most of the plugins modifiable messages are in here. If you want to change disaster names, items, or world forecasts, 
#                    then this is the file to go to! This is also the file to translate to different languages, if you are looking for a language check the discord if someone 
#                    has posted one. If you are translating yourself, please feel free to let me know and share it in the discord.
#
#   "data/" - This is a folder that should generally NOT be touched and is used to store data for the plugin such as timers, regen settings, etc.
#
###############################################################################################################################################################################
#
# Thank you for playing, I really do hope you enjoy the plugin! Feel free to reach out to me on the discord for any help you may need or to report bugs.
#
# Discord: https://discord.gg/MhXFj72VeN
# Spigot Page: https://www.spigotmc.org/resources/deadlydisasters-pro.100918/
# Source: (Available! Contact me in the discord for access)
#
###############################################################################################################################################################################
#
# Below this is the general configurations for the plugin.
#
###############################################################################################################################################################################

general:
    # If set to true then admins will receive a message about updates for the plugin upon joining if any are available.
    update_notify_admins: true
    # If set to true then admins will be alerted when new content is added to the custom disaster catalog.
    catalog_notify: true
    # Debug messages will send error info to the console for some errors. Turn this off if your console is getting spammed with errors.
    debug_messages: true
regeneration:
    # The amount of blocks regenerated per tick for the forceRegeneration command.
    force_regen_blocks_per_tick: 10000
    # This controls if data is saved to a database upon server stopping to persist regen data and allow it to be loaded next time the server is started. This can take a while!
    save_regen_data: true
    # This controls how many blocks per tick are loaded from saved regeneration data after server startup. Increase this number if you want regeneration data to load faster at the cost of TPS.
    load_regen_data_throttle: 1000

###############################################################################################################################################################################
#
# ITEMS
#
# If you are using the UltimateContent add on plugin, which adds many custom items and mobs to the game. This is the settings section for the custom items and enchants.
# I highly recommend you check out UltimateContent if you haven't heard about it, it is also developed by me and really completes this plugin with the custom items and mobs.
#
# Ultimate Content Spigot Page: https://www.spigotmc.org/resources/ultimatecontent.118256/
#
###############################################################################################################################################################################

items:
    # The enchanted book with the basic coating enchant (Apply to a helmet for immunity to acid rain)
    basic_coating_book:
        # The chance of this book spawning in a naturally generated chest (mineshafts, dungeons, etc.)
        loot_table_chance: 1.0