general:
    # If set to true then admins will receive a message about updates for the plugin upon joining if any are available
    update_notify: true
    # If set to true then admins will be alerted when new content is added to the custom disaster catalog
    catalog_notify: true
    # If set to true then disasters will be automatically enabled on new world creations
    auto_enable_on_generation: true
    # If set to true then custom mobs naturally spawning will automatically be enabled on new world creations
    auto_enable_natural_spawning: true
    # Debug messages will send some error info to the console for some errors
    debug_messages: true
    # Custom name support is a new option added in 13.0 before 13.0 some items used the custom names to identify themselves in the code and activate abilities, this can be an exploit since anyone can use an anvil to rename an item and then get the abilities of the custom item. Since the start of 13.0 all custom names have been switched for nbt to patch this exploit but because of this any previously spawned custom items will no longer work, if this is a problem for you then you can revert this change by setting this field to true
    custom_name_support: false
    # Toggle if special limited time events should get enabled or not
    special_events: true
protection_settings:
    # Blacklisted mob types are mob types that are unaffected by all disasters (Keep in mind that disasters which displace the land can affect these entities e.g. Entity falling with Sinkhole)
    blacklisted_mob_types:
    - ender_dragon
    - wither
messages:
    # Modify messages sent by the plugin. Do not set this to be empty it will not work, if you do not want any messages then turn off event_broadcast in general
    console_error_message: '&cUnable to execute command from console!'
    permission_error: '&cYou do not have permission to use that!'
    # If disaster tips is set to true then disaster broadcasts will include the disasters tip
    disaster_tips: true
    # If set to true then players will be notified in chat of any ongoing limited time events
    event_notifications: true
    destructive:
        level 1: '&aLevel: 1 %disaster% &6event starting at: &a%location% &e(%player%)'
        level 2: '&2Level: 2 %disaster% &6event starting at: &a%location% &e(%player%)'
        level 3: '&bLevel: 3 %disaster% &6event starting at: &a%location% &e(%player%)'
        level 4: '&eLevel: 4 %disaster% &6event starting at: &a%location% &e(%player%)'
        level 5: '&cLevel: 5 %disaster% &6event starting at: &a%location% &e(%player%)'
        level 6: '&4&lLevel: 6 %disaster% &6event starting at: &a%location% &e(%player%)'
    weather:
        level 1: '&6A &2very short %disaster% &6is about to begin'
        level 2: '&6A &ashort %disaster% &6is about to begin'
        level 3: '&6A &blong %disaster% &6is about to begin'
        level 4: '&6A &every long %disaster% &6is about to begin'
        level 5: '&6An &cextremely long %disaster% &6is about to begin'
        winds:
            level 1: '&aVery light &fWinds &6are approaching'
            level 2: '&bLight &fWinds &6are approaching'
            level 3: '&9Strong &fWinds &6are approaching'
            level 4: '&eVery strong &fWinds &6are approaching'
            level 5: '&cExtremely strong &fWinds &6are approaching'
            level 6: '&4&lSeverely strong &fWinds &6are approaching'
    # Make a sound play when a disaster message is broadcasted as an extra indicator, set to NONE for no sound. All sounds can be found here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    start_sound:
        sound: 'NONE'
        volume: 1.0
        pitch: 1.0
    misc:
        plague:
            started: '&eA mob has contracted the &0Black Plague'
        purge:
            started: 'Level: %level% &cHorde is assembling, &6%player% &cwill be purged...'
            ended: '&eThe horde is clearing up..'
        world_messages:
            # Allows disaster difficulty messages to be sent when a player switches or joins worlds
            allow_world_messages: true
            # Shows difficulty messages to everyone
            show_world_messages_to_not_opped: false
            message: '&bDifficulty is set to %difficulty% &bon &d%world%'
# Individual settings for disasters (Universal settings such as 'volume' and 'time' are only described in sinkholes and sandstorms)
sinkhole:
    # Delay in seconds before the disaster occurs after it has been broadcasted
    start_delay: 0
    # How fast sinkholes fall. This effects performance
    speed: 5
    # Size multiplier
    size: 1.0
    # Controls if lava gets placed or not at the bottom of sinkholes (Lava is never placed in sinkholes in end type worlds)
    place_lava: true
    # The minimum height the disaster can spawn at
    min_height: 50
    # Max level this specific disaster can reach
    max_level: 6
    # The disaster frequency affects how often a disaster can happen, it can be any value between 0.0 meaning it will never happen and 1.0 meaning it will always have a chance to happen
    frequency: 1.0
    # Volume multiplier for sounds related to this disaster
    volume: 1.0
    # This will change the name of the disaster in game
    name: '&eSinkHole'
earthquake:
    start_delay: 0
    # How fast earthquakes move. This effects performance
    tick_speed: 5
    size: 1.0
    # Tilt is how much earthquakes can fall off their path. The higher the number the more natural earthquakes will be but more blocks will be missed
    tilt: 0.3
    # Force multiplier for how strong earthquakes can throw nearby entities
    force: 1.0
    # Controls if lava gets placed or not at the bottom of earthquakes (Lava is never placed in earthquakes in end type worlds)
    place_lava: true
    min_height: 50
    max_level: 6
    frequency: 1.0
    volume: 1.0
    name: '&8Earthquake'
cavein:
    start_delay: 0
    size: 1.0
    # Damage done by cave-in roof blocks
    damage: 7.0
    # The max amount of falling blocks that can exist at once for a cavein, lower values means caveins will take longer to finish
    max_falling_blocks: 800
    # For caveins only this will be the max height at which caveins can spawn at
    min_height: 50
    max_level: 6
    frequency: 1.0
    volume: 1.0
    name: '&7Cave In'
tornado:
    start_delay: 0
    # The multiplier for the amount of particles that spawn in tornados (By default 1.0 is the max)
    particleAmount: 1.0
    size: 1.0
    # Multiplier for how long tornados last
    time_multiplier: 1.0
    # The speed at which entities move in tornados, NOT how fast tornados move!
    speed: 1.0
    # The width of the tornado, higher number means skinnier tornados
    width: 150
    # Block pickup range is the multiplier for how far blocks from the tornado can be picked up
    block_pickup_range: 1.0
    # Max entities that can be involved in tornados, alive entities always take priority
    max_entities:
        level 1: 200
        level 2: 300
        level 3: 500
        level 4: 800
        level 5: 1000
        level 6: 2000
    min_height: 60
    max_level: 6
    frequency: 1.0
    volume: 1.0
    name: '&fTornado'
geyser:
    start_delay: 0
    # How much damage water geysers do to entities per disaster tick. Entities with fire resistance will not be burned
    water_damage: 1.5
    min_height: 5
    max_level: 6
    frequency: 1.0
    volume: 1.0
    name: '&9Water Geyser/&cLava Geyser'
tsunami:
    start_delay: 0
    # The minimum depth of water needed for a tsunami to occur above. Tsunamis can only occur in ocean biomes
    minimum_depth: 15
    size: 1.0
    # Damage to entities inside the tsunami every disaster tick
    damage: 3.0
    # If set to true then tsunamis will clear the water shortly after
    remove_water: true
    min_height: 50
    max_level: 6
    frequency: 1.0
    volume: 1.0
    name: '&1Tsunami'
supernova:
    start_delay: 0
    size: 1.0
    # This changes how many particles spawn in supernovas (Higher number means less particles)
    particle_multiplier: 1.0
    # Flash toggles the flashing of the supernova
    flash: true
    # Place fire toggles whether fire can be placed by the supernova or not
    place_fire: true
    # If set to true then explosion particles can be seen from very far away by players but this drastically affects performance
    far_particles: true
    # Controls how fast the crystal falls from the sky
    fall_speed_multiplier: 1.0
    min_height: 55
    max_level: 6
    frequency: 0.3
    volume: 1.0
    name: '&3Supernova'
hurricane:
    start_delay: 0
    size: 1.0
    # How long hurricanes last in seconds
    time: 180
    # Chance of lightning striking a player, every higher level will have a 10 fold higher chance to strike, the higher this value means the less likely lightning will strike
    lightning_frequency: 1.0
    # The minimum force of wind required to break blocks near players
    block_break_force: 0.04
    wind_height: 60
    min_height: 60
    max_level: 6
    frequency: 1.0
    volume: 1.0
    name: '&7Hurricane'
purge:
    start_delay: 10
    # How many mobs spawn for each level
    horde_size:
        level 1: 8
        level 2: 13
        level 3: 20
        level 4: 25
        level 5: 35
        level 6: 50
    # Will give the targeted player a progress boss bar and foggy world effects
    boss_bar: true
    # Change the name of the bossbar
    bar_title: 'Horde'
    # The despawn speed is how fast mobs from the horde clear up in ticks
    despawn_speed: 40
    # Spawn distance is how far away the horde mobs spawn from the player, don't set this too high or the mobs will just despawn
    spawn_distance: 25
    min_height: 0
    max_level: 6
    frequency: 0.3
    volume: 1.0
plague:
    start_delay: 0
    # Control which types of mobs are immune to the plague, list of entity type names are available here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
    blacklisted_mobs:
    - ender_dragon
    - wither
    - elder_guardian
    - armor_stand
    - warden
    # Max number of entities that can be infected
    max_infected_mobs: 50
    max_level: 6
    frequency: 0.3
    name: '&0Black Plague'
sandstorm:
    # Delay in seconds for disaster to begin after the event message is broadcast
    start_delay: 5
    time:
        # How long the disaster will last in seconds for each level
        level 1: 30
        level 2: 60
        level 3: 120
        level 4: 200
        level 5: 300
    # If set to true then after sandstorms end all mobs related will have a chance of placing a skeleton skull down before despawning
    mobs_drop_skulls: true
    # If set to true then entities inside sandstorms will suffer from wither
    wither_effect: true
    # Mob spawn rate is the chance of a custom mob spawning per sandstorm spawn tick
    mob_spawn_rate: 25.0
    # Particle max distance means the radius in blocks players can see sand particles on the X and Z axis
    particle_max_distance: 6
    # Particle Y range is the Y level range that sand particles can be displayed at, so higher the number means the further away you can see sand on the Y axis
    particle_Y_range: 10
    # Particle multiplier of sand particles
    particle_multiplier: 1.0
    min_height: 50
    max_level: 5
    frequency: 1.0
    volume: 1.0
    name: '&eSandstorm'
blizzard:
    start_delay: 5
    time:
        level 1: 30
        level 2: 60
        level 3: 120
        level 4: 200
        level 5: 300
    # If set to true then entites can freeze into solid ice during blizzards
    freeze_entities: true
    # If set to true then entites frozen in ice will despawn out of render distance
    despawn_frozen_entities: false
    # If set to true then players wearing leather armor set pieces will take reduced damage in blizzards
    leather_armor_protection: true
    # The damage done to mobs every storm tick
    damage: 0.75
    # The min freezing height is the minimum Y level entities must be to freeze solid, all entities below this will just die instead
    min_freezing_height: 60
    # Particle max distance means the radius in blocks players can see blizzard particles on the X and Z axis
    particle_max_distance: 10
    # Particle Y range is the Y level range that blizzard particles can be displayed at, so higher the number means the further away you can see snow on the Y axis
    particle_Y_range: 10
    # Particle multiplier of snow particles
    particle_multiplier: 1.0
    min_height: 50
    max_level: 5
    frequency: 1.0
    volume: 1.0
    name: '&9Blizzard'
acidstorm:
    start_delay: 5
    time:
        level 1: 30
        level 2: 60
        level 3: 120
        level 4: 200
        level 5: 300
    # Damage done to entities in acid rain
    damage: 1.0
    # If set to true then metal items will melt if left in acid rain such as iron, gold, and chainmail
    melt_dropped_items: true
    # If set to true then entities wearing metal armor such as iron, gold, or chainmail will take extra damage to their armor
    melt_armor: true
    # Particle max distance means the radius in blocks players can see acid rain particles on the X and Z axis
    particle_max_distance: 7
    # Particle Y range is the Y level range that acid rain particles can be displayed at, so higher the number means the further away you can see acid rain on the Y axis
    particle_Y_range: 10
    # Particle multiplier of acid rain particles
    particle_multiplier: 1.0
    # The range from players that blocks are affected by acidic rainfall (Some blocks change, some are destroyed, ex. metals, crops, etc.)
    block_damage_range: 50
    # The rate multiplier of how many blocks around players change
    block_change_rate: 1.0
    # Multiplier for how often slimes can spawn near players
    slime_spawn_rate: 1.0
    # Toggle if crops can get poisoned in acid rain or not
    poison_crops: true
    # Control what effects are given to entities in acid storms (remove and add, potions must be the vanilla name in game and formatted as follows: POTION_NAME: GAME_TICKS)
    effects:
        blindness: 20
        poison: 10
    # Control what blocks are changed to what in acid rain (remove and add, format is as follows: VANILLA_BLOCK_NAME: NEW_VANILLA_BLOCK_NAME)
    block_changes:
        iron_block: air
        iron_bars: air
        iron_trapdoor: air
        gold_block: air
        rail: air
        powered_rail: air
        activator_rail: air
        detector_rail: air
        hopper: air
        cauldron: air
        heavy_weighted_pressure_plate: air
        light_weighted_pressure_plate: air
        stone: cobblestone
        cobblestone: air
        stone_bricks: cracked_stone_bricks
        iron_ore: cobblestone
        deepslate_iron_ore: deepslate
        gold_ore: cobblestone
        deepslate_gold_ore: deepslate
        copper_ore: cobblestone
        deepslate_copper_ore: deepslate
    min_height: 50
    max_level: 5
    frequency: 0.6
    volume: 1.0
    name: '&aAcid Storm'
soulstorm:
    start_delay: 5
    time:
        level 1: 30
        level 2: 60
        level 3: 120
        level 4: 200
        level 5: 300
    # If set to true then lost souls will spawn around players in soulstorms
    spawn_souls: true
    min_height: 0
    max_level: 5
    frequency: 0.6
    volume: 1.0
    name: '&3Soul Storm'
extremewinds:
    start_delay: 5
    time:
        level 1: 60
        level 2: 60
        level 3: 80
        level 4: 100
        level 5: 120
        level 6: 120
    force:
        # The force of the wind for each level. This will have a big impact on performance
        level 1: 0.03
        level 2: 0.06
        level 3: 0.1
        level 4: 0.14
        level 5: 0.18
        level 6: 0.3
    # Max particles displayed for each player
    max_particles: 150
    # Winds have a smart algorithm to determine if you are in a building or not, this value is how many blocks it should check for a roof, the higher a number the more performance heavy it will be especially for big servers
    interior_height_distance: 6
    # How strong winds need to be to rip blocks from buildings
    block_break_force: 0.1
    # This controls the minimum Y level that winds can affect entities
    wind_height: 50
    # Controls if entities are pushed by winds or not
    push_entities: true
    min_height: 60
    max_level: 6
    frequency: 0.6
    volume: 1.0
    name: '&fExtreme Winds'
meteorshowers:
    start_delay: 5
    time:
        level 1: 30
        level 2: 60
        level 3: 80
        level 4: 100
        level 5: 120
    # If set to true then when a meteor storm begins it will temporarily set the time to night
    set_night: true
    # Maximum amount of meteors that can exist at a time. This will impact performance
    max_meteors: 20
    # How often meteors update. This will effect performance
    tick_speed: 1
    # How long in seconds smoke particles remain from meteor impact zones
    smoke_time: 15
    min_height: 60
    max_level: 5
    frequency: 0.6
    volume: 1.0
    name: '&5Meteor Shower'
endstorm:
    start_delay: 5
    time:
        level 1: 60
        level 2: 90
        level 3: 120
        level 4: 150
        level 5: 200
    # The furthest amount of blocks entities can randomly teleport away from in an end storm
    max_tp_range: 10
    # Max number of void mobs that can exist during an end storm
    max_rift_entities: 15
    min_height: 0
    max_level: 5
    frequency: 1.0
    volume: 1.0
    name: '&5End Storm'
solarstorm:
    start_delay: 5
    time:
        level 1: 60
        level 2: 90
        level 3: 120
        level 4: 150
        level 5: 200
    # Will change the time to sunset if set to true
    set_sunset: true
    # Chance of catching fire every storm tick for entities near heat sources
    fire_catch_chance: 30.0
    # Rate of how much fire spawns near players
    fire_spawn_rate: 1.0
    # Control the size of fireball explosions
    fireball_explosion_size: 3.0
    min_height: 60
    max_level: 5
    frequency: 1.0
    volume: 1.0
    name: '&eSolar Storm'
custom:
    # This frequency setting is an overall chance of a custom disaster occurring, 1.0 means only custom disasters can happen
    frequency: 0.2
customentities:
    # If set to true then custom mobs can spawn, setting this to false will keep the plugin more vanilla
    allow_custom_mobs: true
    # If set to true then custom items can be dropped from custom mobs
    allow_custom_drops: true
customitems:
    # The item lore characters per line means the max characters per line in custom items lore, this is to avoid text going off the screen. Not all custom items use this!
    item_lore_characters_per_line: 40
    # Control which custom recipes are enabled
    recipes:
        snow_globe: true
        easter_basket: true
        pumpkin_basket: true
    items:
        basic_coating_book:
            chest_spawn_rate: 1.0
            # Chance of librarian acquiring this item as a trade
            librarian_trade_chance: 7.0
        plague_cure:
            # Chance of cleric acquiring this item as a trade
            cleric_trade_chance: 5.0