name: DeadlyDisasters
version: ${project.version}
author: JewishBanana
main: ${mainClass}
description: Adds deadly disasters to the game.
api-version: 1.17
softdepend: [WorldGuard, Towny, GriefPrevention, Lands, Kingdoms, CoreProtect, RealisticSeasons, UIFramework, UltimateContent]

commands:
    disasters:
        usage: /disasters <help|start|stop|regenerate|fastRegenerate|config|blacklist|timers>...
        description: Universal command for the plugin. Use /disasters help <command>, for more information.
    towndisasters:
        usage: /towndisasters <on|off> [player]
        description: Turn on or off disasters for residents town
        
permissions:
    deadlydisasters.*:
        description: Gives access to all commands of DeadlyDisasters.
        children:
            deadlydisasters.help: true
            deadlydisasters.start: true
            deadlydisasters.stop: true
            deadlydisasters.regenerate: true
            deadlydisasters.fastRegenerate: true
            deadlydisasters.config: true
            deadlydisasters.blacklist: true
            deadlydisasters.timers: true
            deadlydisasters.achievements: true
            deadlydisasters.towny: true
    deadlydisasters.help:
        description: Allows you to use the help command.
    deadlydisasters.start:
        description: Allows you to start disasters via command.
    deadlydisasters.stop:
        description: Allows you to stop disasters via command.
    deadlydisasters.regenerate:
        description: Allows the use of the regenerate command.
    deadlydisasters.fastRegenerate:
        description: Allows the use of the fastRegenerate command.
    deadlydisasters.config:
        description: Allows the use of the config command.
    deadlydisasters.blacklist:
        description: Allows the use of the blacklist command.
    deadlydisasters.timers:
        description: Allows the use of the timers command.
    deadlydisasters.achievements:
        description: Allows the use of the achievements command.
        default: true
    deadlydisasters.towny:
        description: Allows the use of the towndisasters command.