name: DeadlyDisasters
version: 10.0
author: davidclue
main: deadlydisasters.general.Main
description: Adds deadly disasters to the game.
api-version: 1.14
softdepend: [WorldGuard, CoreProtect, Towny, GriefPrevention, Lands, RealisticSeasons, Kingdoms]

commands:
    disasters:
        usage: /disasters <enable|disable|start|mintimer|reload|help|summon|give|difficulty|language|catalog|whitelist|listplayer|config>...
        description: Universal command for the plugin. Use /disasters help, for more information.
        
permissions:
    deadlydisasters.*:
        description: Gives access to all commands of DeadlyDisasters.
        children:
            deadlydisasters.start: true
            deadlydisasters.help: true
            deadlydisasters.modify: true
            deadlydisasters.whitelist: true
            deadlydisasters.listplayer: true
            deadlydisasters.summon: true
            deadlydisasters.give: true
    deadlydisasters.start:
        description: Allows you to start disasters via command.
    deadlydisasters.help:
        description: Allows you to use the help command.
    deadlydisasters.modify:
        description: Allows the use of enable/disable/mintimer/difficulty/language/catalog/reload/config commands to modify functional settings of the plugin.
    deadlydisasters.whitelist:
        description: Allows the use of the whitelist command.
    deadlydisasters.listplayer:
        description: Allows the use of the listplayer command.
    deadlydisasters.summon:
        description: Allows the use of the summon command.
    deadlydisasters.give:
        description: Allows the use of the give command.